### PR TITLE
Bugfix/braces and recursive objects

### PR DESCRIPTION
**Pull request by cocytus**
1. Always output {} on if statements.
2. Handle recursive types.

### CODE REVIEW

**Comment by jnwltr** [comment]
@cocytus Thanks a lot for your PR. Interesting, you are making it to https://github.com/jnwltr/swagger-angular-generator/tree/rc2 already. Have you tried using the store already?

Regarding you changes:

1. Cyclic types -> great, I fully approve the change.
2. Linter -> 2 programmers have 3 opinions. I know that I am not in majority with one-liner `if` acceptance, but believe that's very good in some cases. Linting nuances are often a matter of habit, one gets used to them pretty fast. Wouldn't you have an idea how to solve this issue in a more general way in order not to force the users of the generator to a particular style? I was considering running *autofix* script on generated files (so autofixable deviations would be acceptable).

What do you think?

**Comment by cocytus** [comment]
Added it to the rc2 branch since I thought that was the -rc version on NPM which i added to my project? This is how i discovered the recursive bug, since it's not there on the 1. versions? Maybe my test on 1.x was just faulty.

Anyway: I have not tried the store. In fact, our project does not use ngrx, so adding it generates a lot of errors when compiling. There should be an option to generate/not generate the store.

As for linting: I like oneliners (possibly on the next line even) without braces. I don't think I've had a bug in the last 20 years due to missing {}. But, that's not the way things to be moving - "everybody" likes braces everywhere apparently, and "all" linters/codeanalyzers seems to default to enforcing them. So I just go with the flow, and thought maybe this repo would like to as well? I have no strong feelings on the matter.

Now, when it comes to generating code to fit different projects - I don't think that's really important, as you can just add a tslint.json where all rules are removed in the generated-files folder. In general, generated files should not be required to be held to the same linting rules as manually written code.

**Comment by jnwltr** [comment]
So if you agree, let's merge w/o braces (linter-related) change.
I agree to make store/forms optional, once done together with README.md, we will merge to develop and make v2 official.

**Comment by cocytus** [comment]
Removed braces change, added --no-store parameter.

**Comment by jnwltr** [comment]
Great, thanks!

**Pull request merged**
