### PR TITLE
generate true enums if key-val description available

### PR DESCRIPTION
**Pull request by sangecz**
for a given API method parameter:
```
...
{
  "name": "objectType",
  "in": "query",
  "description": "The object type Options: [0 = Undefined, 1 = Category, 2 = Article]",
  "required": true,
  "type": "integer",
  "format": "int32",
  "enum": [0, 1, 2]
},
...
```
instead of this output:
```
export type ObjectTypeTagsParamsEnum =
  '0' |
  '1' |
  '2'
```
it will create:
```
export enum ObjectTypeTagsParamsEnum {
  Undefined = '0',
  Category = '1',
  Article = '2',
}
```

This will give you convinient  usage in eg. switch case where instead of:
```
case '1'
```
you can reference enum like that:
```
case ObjectTypeTagsParamsEnum.Category
````

### CODE REVIEW

**Comment by jnwltr** [comment]
Thanks, @sangecz. Do you consider this `...[key = value, ...]` format in `description` field as something generic, or is that rather an ad hoc solution? I feel key-value enums should be modelled another way (although neither OpenAPI v3 addresses that).

In other words, why did you choose this solution?

**Comment by sangecz** [comment]
@jnwltr I consider following format in description: `...[val = key, ...]` because it's automatically generated from enum eg. (.NET):
```
public enum TagObjectType {
 Undefined = 0,
 Category = 1,
 Article = 2
}
``` 

@leiserfg that's true but not very usefull

**Comment by jnwltr** [comment]
Is that a stable/documented feature?

I fully acknowledge `enum` with named values is more self-explanatory than `type` composed of value strings. What I would on the other hand fear of, is relying on proprietary usage of description field.

Imagine a situation somebody else uses square brackets (I am not emphasising the fact the way you parse the string could be more robust) without intention to show key-value pairs. Then we would break the code (generate unusable type).

So I am afraid in case of the proposed solution:
- false negatives overrule false positives in their impact, and
- we would rely on a proprietary solution without any guarantee it would work this way in the future.

What do you think? Any other idea how to solve this, if you feel it's very beneficial?

**Comment by sangecz** [comment]
afaik, it's custom solution to generate enum description that way (our API team does that).

I don't see other way than more robust parser with fallback and to introduce this as possible feature of the generator.

If you want to close this PR for lack of standardisation of its feature, I totally understand, so go ahead :)

**Comment by jnwltr** [comment]
I was thinking of the following solutions:
- optional feature,
- generic plugin-like system, and
- customizable pre-processor combined with proprietary extension of the format

but not think any of them is worth the effort for this feature. So let's abandon it for now as you propose, but we can keep it in mind, and come back to it once we have a better idea or situation changes.

Anyway, thanks a lot for this use case, proposal of its solution, and the follow-up discussion.

**Pull request closed without merging**
