### PR TITLE
Export type alias when def is type alias

### PR DESCRIPTION
**Pull request by soundTricker**
currently, swagger-angular-generator generate invalid definition file when swagger.json has type alias definition like below, because swagger-angular-generator generate empty defs file and import it from models.ts.

```json
"definitions": {
    "Alias": {
      "type": "integer",
      "description": "Alias",
      "format": "int32"
    },
    "UseAlias": {
      "type": "object",
      "required": [],
      "properties": {
        "alias": {
          "$ref": "#/definitions/Alias"
        }
      }
    }
}
```
This PR support type alias using typescript type alias.

### CODE REVIEW

**Comment by fazpu** [comment]
I am sorry for the late response, it is good from my side. @jnwltr?

**Comment by jnwltr** [comment]
Please, can you recheck on https://github.com/jnwltr/swagger-angular-generator/pull/72/files (after merger on on its branch now)? I believe we are having the same thing covered there (check https://github.com/jnwltr/swagger-angular-generator/blob/feature/form-map/demo-app/client/swagger-files/unit-test-swagger.json#L984).

**Comment by jnwltr** [comment]
I believe it is solved by https://github.com/jnwltr/swagger-angular-generator/pull/72.

**Comment by soundTricker** [comment]
@jnwltr unfortunately, it's not fixed #72. Currently generator create empty file, when there is type alias definition like below.

```
"definitions": {
"RefStatus": {
      "format": "int32",
      "type": "integer"
    }
}
```

**Comment by soundTricker** [comment]
@jnwltr Can I re-send PR of this issue?

**Pull request closed without merging**
